### ISSUE TITLE
Implement `pauseTest` and `resumeTest` helpers

### ISSUE THREAD

**Issue by dwickern** [cibernox/ember-native-dom-helpers#10]
This would be nice for debugging, and consistent with the acceptance test APIs. What do you think?

Implementation can be something like
```
await wait();
Ember.run.begin();
await wait();
```

**Comment by rwjblue** [comment]
👍 - Seems good to me!

**Comment by rwjblue** [comment]
Should also include `resumeTest` (recently added to ember-testing for acceptance tests).

**Comment by rwjblue** [comment]
Acceptance test implementation is here https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers/pause_test.js

**Comment by cibernox** [comment]
Edited the title and added Help wanted label.

The requirement is that it must work both in integration and acceptance.

**Comment by ro0gr** [comment]
`pauseTest` is [implemented](https://github.com/emberjs/ember-test-helpers/commit/f065e1fb5646d1cdd4c72e52dfe25496b8dbabea) in@ember/test-helpers.

Should this issue be closed now?
