### ISSUE TITLE
Support fillIn for [contenteditable] elements

### ISSUE THREAD

**Issue by ro0gr** [cibernox/ember-native-dom-helpers#100]
It will improve ~`ember-native-dom-event-dispatcher`~ `ember-native-dom-helpers` [integration]( https://github.com/san650/ember-cli-page-object/blob/88fad42f23837020f40ffe57bfa2c56169aba39f/addon/-private/execution_context/integration.js#L42) with `ember-cli-page-object`.

Any objections to have [`[contenteditable]`](https://github.com/san650/ember-cli-page-object/blob/88fad42f23837020f40ffe57bfa2c56169aba39f/addon/-private/execution_context/helpers.js#L22) on board?

**Comment by cibernox** [comment]
No, it sounds like a good addition. I'd take a PR adding that.
