### ISSUE TITLE
Doesn't Work With IE11

### ISSUE THREAD

**Issue by jherdman** [cibernox/ember-native-dom-helpers#111]
Running tests with IE11 I see the following error:

<img width="932" alt="screen shot 2017-09-27 at 2 35 58 pm" src="https://user-images.githubusercontent.com/3300/30930961-4e184162-a391-11e7-9b38-d00b658910f1.png">

The problem seems to be that the regenerator runtime assumes that Promise is natively defined by the browser, which is sadly not the case in IE11.

**Comment by cibernox** [comment]
@jherdman did you install `ember-maybe-import-regenerator`?

**Comment by jherdman** [comment]
I did not. Clearly I am an idiot /me hits head against the wall after reviewing the README.

**Comment by jherdman** [comment]
OK, I hate to dredge this back up, but... things are still broken after installing the maybe-import-regenerator. Same error as above.

**Comment by rwjblue** [comment]
Ya, you would need:

```
// vendor/promise-shim.js
if (typeof Promise === ‘undefined’) {
  self.Promise = Ember.RSVP.Promise;
}
```

Then add `app.import(‘vendor/promise-shim.js’)` to `ember-cli-build.js`.
