### ISSUE TITLE
keypress key vs keyCode inconsistency across browsers

### ISSUE THREAD

**Issue by ro0gr** [cibernox/ember-native-dom-helpers#112]
This works in Chrome/Firefox but in IE11 and phantomJS:
```js
    find('input').addEventListener('keypress', e => {
      assert.equal(e.keyCode, 13);
    });

    triggerEvent(find('input'), 'keypress', {
      key: 13,
      // keyCode: 13 results to NaN
    });
```

works in IE11 but not in Chrome:
```js
    find('input').addEventListener('keypress', e => {
      assert.equal(e.keyCode, 13);
    });

    triggerEvent(find('input'), 'keypress', {
      keyCode: 13 // <=
      // key: 13 results to undefined
    });
```

In case of IE this assert fails with the following `qunit` message:

> Expected: 13
Result: undefined

also there are [failures in phantomJS](https://travis-ci.org/san650/ember-cli-page-object/jobs/283405793#L2249) I think it's similar to IE.

I can see several tricks around `keyCode` in [`triggerEvent`](https://github.com/cibernox/ember-native-dom-helpers/blob/9132376a0f4e9e2529716016f36b65be1321ec5d/addon-test-support/fire-event.js#L130) but I don't 100% follow what happens here yet.
One thing I'm interested in is that this `keyPress` stuff happens only for the "happy path" when `new KeyboardEvent(type, eventOpts);` succeeds.

Here is a demo app with a [reproduction](https://github.com/ro0gr/ndh-events/blob/master/tests/integration/components/key-press-test.js)

**Comment by cibernox** [comment]
Have you tried the `keyEvent` helper. That is the one you should use for keyboard-related events.

**Comment by ro0gr** [comment]
it works. Thank you!
