### ISSUE TITLE
RFC: add `text` helper

### ISSUE THREAD

**Issue by kellyselden** [cibernox/ember-native-dom-helpers#117]
Just a convenience method:

`find('[data-test-product-banner]').textContent.trim()` => `text('[data-test-product-banner]')`

I'm cool if you don't want it.

**Comment by cibernox** [comment]
My gut feeling, without giving it much thought, is that this could be better served by using an assertion library like https://github.com/simplabs/qunit-dom

At the end, you usually care about the text of an element to assert it equals or contains some control value.

**Comment by rwjblue** [comment]
Agreed RE: qunit-dom (thats what I thought as I read the initial description as well).  

@Turbo87 - Do you have or plan to have any text based assertion helpers?

**Comment by rwjblue** [comment]
Whoops, I should have RTFM, there are a few text assertions mentioned in https://github.com/simplabs/qunit-dom/blob/master/API.md (`hasText` and `includesText`).

**Comment by Turbo87** [comment]
yep, if you're missing any other helpers let me know. happy to add more to `qunit-dom` if something is missing.

**Comment by cibernox** [comment]
Closing then :)
