### ISSUE TITLE
Avoid using MouseEvent.initMouseEvent

### ISSUE THREAD

**Issue by alexander-alvarez** [cibernox/ember-native-dom-helpers#12]
In https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/helpers.js#L69 
we use [MouseEvent.initMouseEvent()] which is deprecated in favor of the plain constructor: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent

Might have issues down the line.

Also curious about the undocumented `+1, +5, +95` here https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/helpers.js#L42

I can change out to use the constructors when I get the chance

[MouseEvent.initMouseEvent()]: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent

**Comment by pixelhandler** [comment]
@alexander-alvarez the `fireEvent` function is taken right off the Ember event method here: https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-testing/lib/events.js#L29-L51 and likewise the `buildMouseEvent` function here: https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-testing/lib/events.js#L60-L85

We can improve as needed. However some deprecated methods are still the most compatible across browsers, so will have to consider that as well.

For example, see https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-testing/lib/events.js#L54 and https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/helpers.js#L58 notice the shift to native events only, no hep from jQuery. MDN recommends using Event constructors vs `document.createEvent` here https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent

So far we started with borrowing the existing acceptance test helper events and made some updates to fix issues regarding using native events and DOM API only (no jQuery).

**Comment by cibernox** [comment]
I can confirm that because I also did the emberjs helpers. The only reason why I use the awful initmouseevent is because of Internet Explorer. We can't drop it until ember 3.0
