### ISSUE TITLE
Allow to pass `HTMLElement`s to helpers (click, tap, fillIn...)

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-native-dom-helpers#27]
Right now helpers expect a selector as first argument that they use to query the DOM and get the HTMLElements. It would be useful if they could receive the HTMLElement itself.

Result: 

```js
let input = find('.my-text-input');
click(input);
fillIn(input);
keyEvent(input, 'keydown', 13);
```

:+1:/:-1:

**Comment by rwjblue** [comment]
:+1:
