### ISSUE TITLE
Focus method used by various events should unfocus what is focused already

### ISSUE THREAD

**Issue by pixelhandler** [cibernox/ember-native-dom-helpers#31]
Heard a comment on the Ember Weekend show, http://emberweekend.com/episodes/actual-newsy-things at 01:10 about focus and how we could also check the DOM and focusout on any currently focused element.

Perhaps in the `focus` method we could use `document.activeElement` to check if an element has focus and fire `blur` or `focusout`

- See https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement

**Comment by pixelhandler** [comment]
@code0100fun @rondale-sc Can you comment here, please :) I think you had some feedback from on the podcast, would be great to capture that here as well.

**Comment by cibernox** [comment]
I also heard the podcast and I was surprised by that. At least if the browser window has the focus, I'd expect `el.focus();` on [this line](https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/focus.js#L26) to also cause a blur on whatever else if focused before.

Perhaps that effect only happens on the branch before, the one were we fake a focus.

**Comment by pixelhandler** [comment]
In CI the browser is not in focus as it's driven by a machine. So yeah the branch of manually firing `focus` could also check for `document.activeElement` but again how could that be necessary as the browser it is not in focus. Well I guess if the tests fires focus somehow it could be true that we'd need to unfocus. So that begs the question should we have a `focus` helper too?

**Comment by cibernox** [comment]
the problem is that (I think) if the browser doesn't has the focus, you cannot obtain `document.activeElement`, so we can't know what to blur. Can we?

**Comment by pixelhandler** [comment]
From Slack, thanks @code0100fun …

> Chase… I'm not sure if Twiddle supports addons fully. I can't import the `click` function. Here is my use case: https://ember-twiddle.com/58027e0abcdbda5ee6001ce01245eac5?openFiles=tests.integration.components.my-component-test.js%2Ctemplates.components.my-component.hbs If you disable tests you can see it working. The test should pass but does not without manaully bluring/focusing

**Comment by pixelhandler** [comment]
@cibernox yeah `document.focus()` will trigger `blur` event on the `document.activeElement`. I added a test in the PR to show that working. The caveat is that that part of the test can only work if the browser window has focus, so skips in CI. Also Chrome, Firefox and Safari pass with the new test in PR #36. However PhantomJS fails so it may be time to abandon PhantomJS.

**Comment by pixelhandler** [comment]
@code0100fun @rondale-sc Please see the PR which adds a test to show that blur does fire as long as the browser window has focus.
