### ISSUE TITLE
find && contains text helper

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-native-dom-helpers#33]
Would it be useful to have a method that returns the element that `contains` text, similar to jQuery?  Some combination of `querySelectorAll` and `Regex`.  I can imagine with a list of elements that one might not know at the outset what index the item they are finding is at.  Any thoughts?

**Comment by snewcomer** [comment]
nvmd.  Just saw the other issues relating to this.  Sry!

**Comment by pixelhandler** [comment]
@snewcomer yeah @cibernox has open issues related, See #23, #32

**Comment by cibernox** [comment]
Apparently the general feeling was to stick the standard CSS3 selectors for now. I have the feeling that we will end up implementing it for popular demand, but it's low in priority. 
In the meanwhile I've implemented it myself like this: https://github.com/cibernox/ember-power-select/blob/master/test-support/helpers/ember-power-select.js#L11-L13
