### ISSUE TITLE
Different rootElement than in jQuery based tests

### ISSUE THREAD

**Issue by simonihmig** [cibernox/ember-native-dom-helpers#63]
Not sure if this is an issue or designed like that by intention, but at least it leads to some CSS selectors not working the same as in jQuery-based tests. 

When rendering a component in integration tests, the resulting DOM will look like this:

```html
<div id="ember-testing" class="ember-application">
  <div id="ember139" class="ember-view">
    <div id="ember187" class="my-component"></div>
  </div>
</div>
```

For `find` the `rootElement` is explicitly set to `#ember-testing`, while for `this.$()` the equivalent is the `#ember139` view. This results in the following incompatible difference when using the `:first-child` selector:

`find(':first-child')` -> `#ember139` (the wrapping view)
`this.$(':first-child')` -> `#ember187` (the actual component under test)

So when migrating, one would have to rewrite all those selectors. I would assume that it should actually behave the same, at least that would make migrating more straightforward. (I actually used this selector in ember-bootstrap quite often)

Would you consider this a bug? If not it should probably be documented. Also relates to #51, could make an automatic migration if this is not considered a bug and will stay like this...

**Comment by cibernox** [comment]
How does the DOM look if you render two components in the same test? Is there still that ember139 wrapper?

**Comment by simonihmig** [comment]
> How does the DOM look if you render two components in the same test? 

the same. 

I digged a bit into it. The wrapping view comes from `ember-test-helpers`: https://github.com/emberjs/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-component.js#L183. 

Here you can see how jQuery's rootElement is set: https://github.com/emberjs/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-component.js#L250-L260

I guess we could use the same for https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/settings.js#L8?

**Comment by cibernox** [comment]
@rwjblue I think I delegate on you. Do you want to have any opinion on your RFC? 
I'm fine with both, although I don't understand why we have this wrapper.

**Comment by mkay581** [comment]
+1 for this. It's fairly a bit odd that the root element of the test DOM using `find()` is different from the root element when using `this.$()`, since, for most cases, the root component element is desired.

Although I can see use cases where getting the test DOM wrapper is necessary. One idea is to allow no parameters to be passed to `find()` and just return the same thing `this.$()` returns. Is that possible?

**Comment by rwjblue** [comment]
Ya, I'm game to fix this so that it generally matches what `this.$()[0]` returns.

**Comment by mkay581** [comment]
Oops, yeah `this.$()[0]` is what I meant--sorry. Maybe we should also make `findAll()` (with no parameters) return `this.$()` also?
