### ISSUE TITLE
Flaky tests for focusout

### ISSUE THREAD

**Issue by simonihmig** [cibernox/ember-native-dom-helpers#65]
I am not sure what this all means, but given a component that listens for `focusout` I get these results:

* `this.$('input').trigger('focusout')` always works
* `this.$('input').trigger('blur')` always works
* `triggerEvent('input', 'focusout')` **never** works
* `triggerEvent('input', 'blur')` *always* works
* `blur('input')` **sometimes** works

I created a reproduction repo here: https://github.com/simonihmig/ember-native-helpers-demo/blob/master/tests/integration/components/foo-bar-test.js

Regarding the `blur` flakiness: it seems it does work when having a fresh test run, or pressing `enter` on `ember t -s`:

![image](https://cloud.githubusercontent.com/assets/1325249/25659221/10b40052-3007-11e7-8bbd-7aafc3b5ee5b.png)

As soon as I reload the Chrome browser window, the test fails:

![image](https://cloud.githubusercontent.com/assets/1325249/25659254/30347844-3007-11e7-9142-e32f9b272d3c.png)

Seems related to the browser-has-focus handling in `blur.js`: as soon as it hits this line (https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/blur.js#L32) it seems to work. I patched that helper locally to always call `fireEvent` and not `el.blur()`, and then it seems to work just fine for me. 

Don't know if that makes sense? Also why `triggerEvent('input', 'focusout')` does not work at all...

**Comment by RuslanZavacky** [comment]
@simonihmig when you've patch it, have you checked if document.activeElement changes when you trigger an event? I think there is a room for improvement for the focusout. The difference is, that it not only relates to testing but to your code as well. If you have code that is doing .focus and .blur, it has to do the same sequence of events, when the browser is not focused.

**Comment by cibernox** [comment]
I also think that the flackyness depends on wether the browser has the focus or not. The reason why jquery events work is probably because they are not "real" event (native).

I think that users should not use `triggerEvent('selector', 'focusout')`, as it's somewhat artificial. Blurring an element fires `focus` on that element, which doesn't bubble and a `focusout` event that does bubble to ancestor elements.

I think that either `triggerEvent(selector, 'blur')` should transparently call `blur(selector)`, or we should show a deprecation/warning/assert and ask the users to use `blur(selector)` instead.

This thoughts are regardless of the actual problem you are describing. I just use this chance to state that I think it should be a single way of focusing/blurring elements.

**Comment by simonihmig** [comment]
> If you are focused on browser window, when tests are running, I suppose it works fine?

No, it was just the opposite! See my first comment, when I hit reload in the browser (so it is focused), it was *not* working. Only when e.g. hitting enter in the `ember t -s` terminal window

I updated the repo a bit, now it `console.log`s the `document.activeElement`. And I added a `focus` call first, which does make a difference: now the flaky test seems to work fine!

So before in my test I had just something like `this.$('input').trigger('focusout');` to trigger some behaviour. As I said this was not working when translating that to `blur('input')` or `triggerEvent('input', 'focusout')`. But like this it seems to work now:

```js
await focus('input');
await blur('input');
```

**Comment by RuslanZavacky** [comment]
ah, yea, @simonihmig it's actually the thing :) If you try to do blur, without focusing into element first, it's not exactly how the browser works, when the user interacts with it :) so in tests, you have to mimic the similar behavior. Before blurring, you have to be focused on an element.

**Comment by cibernox** [comment]
I see. Yeah, you can't blur what it's not focused. It's not how things really work.

@simonihmig We could add assertions for things like that. A lot assertions if that improves developer's ergonomic, since this is not code that you ship in production.

**Comment by simonihmig** [comment]
Yeah, makes sense! I was just naively assuming what was working with jQuery events would work the same with native events...
