### ISSUE TITLE
el.contenteditable check that we use in isFocusable and in focus() need a revamp

### ISSUE THREAD

**Issue by RuslanZavacky** [cibernox/ember-native-dom-helpers#69]
We do use `el.contenteditable` to check if we can focus an element and when we issue `focus` action. The issue with that is, that `contenteditable` *always* has a value, and this value is `inherit` (https://www.w3.org/TR/html5/editing.html#sequential-focus-navigation-and-the-tabindex-attribute). But for the real element to be focused, it should have `contenteditable === true`. 

And as a separate thing, it's not enough just to fix that `contenteditable === true`, we should also add a check for the existence of tabindex. 

I am kinda guilty of just copying this code without truly testing it through :) 

https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/-private/is-focusable.js#L9

**Comment by cibernox** [comment]
I actually found the same thing thanks to the conversion to typescript, but since that is going to take a while we should fix it before.

**Comment by RuslanZavacky** [comment]
I'll hope to look into that next week, as it's currently not a big issue, but for this repo to perform 1-to-1 as browser, we have to make it right :)

**Comment by ro0gr** [comment]
can it be closed?
