### ISSUE TITLE
Support clicking (querying) svg element

### ISSUE THREAD

**Issue by knownasilya** [cibernox/ember-native-dom-helpers#70]
Currently, I get the following error: 

> Error: Failed to execute 'querySelector' on 'Document': '#ember-testing [object SVGPathElement]' is not a valid selector.

**Comment by knownasilya** [comment]
I'm doing the following `await click('.leaflet-interactive');`

**Comment by cibernox** [comment]
I'm pretty sure I know the reason. Hold on still.
