### ISSUE TITLE
selectFiles Seems Broken in Chrome Canary

### ISSUE THREAD

**Issue by jherdman** [cibernox/ember-native-dom-helpers#94]
Given:

```javascript
  await selectFiles(
    '.some-selector',
    [
      new Blob(['test-test'], {
        name: 'foo.jpg',
        type: 'image/jpeg'
      }),
    ]
  );
```

I see the following error message in Chrome Canary (v62):

<img width="699" alt="screen shot 2017-08-08 at 1 04 49 pm" src="https://user-images.githubusercontent.com/3300/29084513-36223906-7c3a-11e7-87b5-62467d61ddb6.png">

**Comment by cibernox** [comment]
@webark May I bring your attention to this?
@jherdman does this work for you on non-canary versions of chrome?

**Comment by webark** [comment]
ya. I was trying to keep things as close to the traditional api as possible, but it looks like now chrome 62 doesn't work, and give a similar error as firefox did, but using a different message. Perhaps we need to abandon the hope that we could maintain the `FileList` object, and just reset it to an array.

**Comment by cibernox** [comment]
In my experience error messages change very little. If we add another Regexp for chrome we might be good for the next 2 years.

**Comment by jherdman** [comment]
No, this also appears to be broken in Chrome v60 too. The file list is empty (i.e. `event.target.files`).

**Comment by webark** [comment]
ya. My only concern is that if both chrome and firefox do not support the mutating of the `FileList` is it worth even trying to do that?

**Comment by webark** [comment]
@cibernox i think just replacing the `FileList` with an array is simpler and being that at least firefox and chrome no longer "support" the other way munching it, we should just keep with that. Take a look at #95 and let me know what you think.
